language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: test
      name: (angular)
      script: ./scripts/angular/test.sh
    - stage: test
      name: (api)
      script: ./scripts/api/test.sh
    - stage: test
      name: (email)
      script: ./scripts/email/test.sh
