language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - ENVIRONMENT=staging
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: pre-cache
      script: skip

    - stage: test
      name: '(angular)'
      script:
        - git fetch origin master:master
        - lerna ls --since master | grep -q 'angular' || exit 0
        - lerna run test --scope=angular

    - stage: test
      name: '(email)'
      script:
        - git fetch origin master:master
        - lerna ls --since master | grep -q 'email' || exit 0
        - lerna run test --scope=email

    - stage: test
      name: '(api)'
      script:
        - git fetch origin master:master
        - lerna ls --since master | grep -q 'api' || exit 0
        - lerna run test --scope=api
