language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  global:
    secure: hGuFx0oX6SCfzG9cM0sv7huTzaBnClZIZdOObxPXb+gkHxAxi0pseUacoYFoRiZJIZX/GTIi7i2J/vLJn5A8mSvbJRlks21+WPZenkOPXt1+ChvONvmH14RSF5BONq2c9oB1hKsQVKOsGZ6Js23jVuk+MJ83Ry84xdmndi9E0UkQPfUaja5Lg+Vr1xxwHCRsC7FWnAd87uuwZALCV86STM+PfVgmetcVU8fgVXXfvw9MexSy+rotFt+gjE7QO/Xqzw/GeI61iEMz4Svyyj9gH5+PRSO4Ct4q898Rqs7aOag6FwMt1+ZyHUhSPdnDeGz/E4Yd2B4/70kVowVLEOdmcwDcI99NQ20X0UuSbZLpgbU2f1EqtNZv3im2Y7QYnTyGHy86I39CxWc1FEzLFNon/h98NrhqzsAHFfR5l7BYqK3UiAE8P9rqVFMLlqi+QXj8K5++6BMikywZKbZFy2dXLKPjljOJzamN0en9JqbHHD3qtOLVYWTVA6T/BWQQ9GFsIdz+0NpzYYCndTL6TOZYr1NqSEs724gm8qOSkcCwU5oPMpgg3GXCaPBv6skuZA143eoc7h+ovDbqcZqD9agnOuFAKQYeNsY7pTP4C6266tVL2+No0NPxwBgqSRIONKETfMjvFjn6tNdMPhf9qzK7gd0/AHl22PDFtSmbxTJct5M=

is_release: &is_release branch = master AND type != pull_request AND commit_message =~ /chore\(release\)/
is_not_release: &is_not_release commit_message !~ /chore\(release\)/
is_master_is_buildable_commit: &is_master_is_buildable_commit branch = master AND type != pull_request AND commit_message =~ /(feat|fix|perf|refactor)\(?\w*\)?:/

jobs:
  include:
    # - stage: test
      # if: *is_not_release
    #   name: (angular)
    #   script: ./scripts/angular/test.sh
    # - stage: test
      # if: *is_not_release
    #   name: (api)
    #   script: ./scripts/api/test.sh
    # - stage: test
    #   if: *is_not_release
    #   name: (email)
    #   script: ./scripts/email/test.sh
    - stage: release
      if: *is_master_is_buildable_commit
      script: skip
      deploy:
        provider: script
        script: ./scripts/release.sh
        skip_cleanup: true
    - stage: deploy
      if: *is_release
      script: skip
      deploy:
        provider: script
        script: ./scripts/api/deploy.sh
        skip_cleanup: true
